### ISSUE TITLE
Browserify/Webpack: TypeError: URL is not a constructor

### ISSUE THREAD

**Issue by Heath123** [ethanent/centra#6]
When using Browserify or Webpack with this, this error occurs:
![image](https://user-images.githubusercontent.com/13787163/80284480-aaa21280-8716-11ea-892f-340e1b46d632.png)
This can be worked around by editing the code to use url.parse instead, but I don't think this is a proper solution.

**Comment by Heath123** [comment]
Example fix:
https://github.com/Heath123/centra/commit/26a87579e4617764d9596fa90ac3cfc6259a1686

**Comment by ethanent** [comment]
This doesn't really seem to be an issue with Centra, but rather Browserify's implementation of the URL module. I think it would be better to fix this issue with them.
